title: Research Methods
description: Dry lab and wet lab methods, recipes, and SOPs.

collections:
  methods:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "methods"
    values:
      layout: "method"

markdown: kramdown
